FROM r-base:4.6.1

WORKDIR /usr/workspace/
RUN mkdir results/drimseq
RUN << EOF
apt-get update
apt-get install -y libcurl4-openssl-dev libxml2-dev 
RUN R -e "install.packages('BiocManager')"
RUN R -e "BiocManager::install(c('tximport','jsonlite','readr', 'GenomicFeatures','DRIMSeq','txdbmaker'))"

COPY results/samples.csv /usr/workspace/results/samples.csv
COPY script/drimseq.R /usr/workspace/script/drimseq.R
COPY data/ref/gencode.v50.chr_patch_hapl_scaff.annotation.gtf /usr/workspace/data/ref/gencode.v50.chr_patch_hapl_scaff.annotation.gtf
ENTRYPOINT [ "R script/drimseq.R" ]